/* File generated by DarkEdifPreBuildTool v1.0.1.1, part of DarkEdif SDK.
   DarkEdif license is available at its online repository location.
   Copyright of the POW 2o3 extension and all rights reserved by creator of POW 2o3.

   A native Mac extension needs a Objective-C file to generate a Objective-C class.
   This file is required. The POW 2o3 creator may modify the copyright to suit their wishes,
   if they retain the DarkEdif notice (third line).
*/

//----------------------------------------------------------------------------------
// CRunPOW_2o3
//----------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import "MMF2Lib/MMF2Runtime.h"

#if __cplusplus
extern "C" void POW_2o3_init();
extern "C" void POW_2o3_dealloc();
// Doesn't take a cptr, but you can't use it without SDK initialization - POW_2o3_init()
extern "C" int POW_2o3_getNumberOfConditions();
extern "C" long POW_2o3_conditionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void POW_2o3_actionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void POW_2o3_expressionJump(void * cppExtPtr, int ID);
extern "C" void * POW_2o3_createRunObject(void * file, void * cob, int version, void * objCExtPtr);
extern "C" short POW_2o3_handleRunObject(void * cppExtPtr);
extern "C" void POW_2o3_destroyRunObject(void * cppExtPtr, bool bFast);
extern "C" void POW_2o3_pauseRunObject(void * cppExtPtr);
extern "C" void POW_2o3_continueRunObject(void * cppExtPtr);
#endif

static int initedPOW_2o3CPP = 0;

@interface CRunPOW_2o3 : CRunExtension
{
@public
	void * safetyPtr; // used to ensure cptr lookups are using a valid pointer
	void * cptr; // For 32-bit and 64-bit
	CValue * expRet;
}
-(int)getNumberOfConditions;
-(int)handleRunObject;
-(BOOL)createRunObject:(CFile*)file withCOB:(CCreateObjectInfo*)cob andVersion:(int)version;
-(void)destroyRunObject:(BOOL)bFast;
-(BOOL)condition:(int)num withCndExtension:(CCndExtension*)cnd;
-(void)action:(int)num withActExtension:(CActExtension*)act;
-(CValue*)expression:(int)num;
-(void)pauseRunObject;
-(void)continueRunObject;

@end
