/* File generated by DarkEdifPreBuildTool v1.0.1.1, part of DarkEdif SDK.
   DarkEdif license is available at its online repository location.
   Copyright of the Font Embed Object extension and all rights reserved by creator of Font Embed Object.

   A native Mac extension needs a Objective-C file to generate a Objective-C class.
   This file is required. The Font Embed Object creator may modify the copyright to suit their wishes,
   if they retain the DarkEdif notice (third line).
*/

//----------------------------------------------------------------------------------
// CRunfontembed
//----------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import "MMF2Lib/MMF2Runtime.h"

#if __cplusplus
extern "C" void fontembed_init();
extern "C" void fontembed_dealloc();
// Doesn't take a cptr, but you can't use it without SDK initialization - fontembed_init()
extern "C" int fontembed_getNumberOfConditions();
extern "C" long fontembed_conditionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void fontembed_actionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void fontembed_expressionJump(void * cppExtPtr, int ID);
extern "C" void * fontembed_createRunObject(void * file, void * cob, int version, void * objCExtPtr);
extern "C" short fontembed_handleRunObject(void * cppExtPtr);
extern "C" void fontembed_destroyRunObject(void * cppExtPtr, bool bFast);
#endif

static int initedfontembedCPP = 0;

@interface CRunfontembed : CRunExtension
{
@public
	void * safetyPtr; // used to ensure cptr lookups are using a valid pointer
	void * cptr; // For 32-bit and 64-bit
	CValue * expRet;
}
-(int)getNumberOfConditions;
-(int)handleRunObject;
-(BOOL)createRunObject:(CFile*)file withCOB:(CCreateObjectInfo*)cob andVersion:(int)version;
-(void)destroyRunObject:(BOOL)bFast;
-(BOOL)condition:(int)num withCndExtension:(CCndExtension*)cnd;
-(void)action:(int)num withActExtension:(CActExtension*)act;
-(CValue*)expression:(int)num;

@end
