/* File generated by DarkEdifPreBuildTool v1.0.1.1, part of DarkEdif SDK.
   DarkEdif license is available at its online repository location.
   Copyright of the UUID Generator extension and all rights reserved by creator of UUID Generator.

   A native Mac extension needs a Objective-C file to generate a Objective-C class.
   This file is required. The UUID Generator creator may modify the copyright to suit their wishes,
   if they retain the DarkEdif notice (third line).
*/

//----------------------------------------------------------------------------------
// CRunUUID_Generator
//----------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import "MMF2Lib/MMF2Runtime.h"

#if __cplusplus
extern "C" void UUID_Generator_init();
extern "C" void UUID_Generator_dealloc();
// Doesn't take a cptr, but you can't use it without SDK initialization - UUID_Generator_init()
extern "C" int UUID_Generator_getNumberOfConditions();
extern "C" long UUID_Generator_conditionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void UUID_Generator_actionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void UUID_Generator_expressionJump(void * cppExtPtr, int ID);
extern "C" void * UUID_Generator_createRunObject(void * file, void * cob, int version, void * objCExtPtr);
extern "C" short UUID_Generator_handleRunObject(void * cppExtPtr);
extern "C" void UUID_Generator_destroyRunObject(void * cppExtPtr, bool bFast);
#endif

static int initedUUID_GeneratorCPP = 0;

@interface CRunUUID_Generator : CRunExtension
{
@public
	void * safetyPtr; // used to ensure cptr lookups are using a valid pointer
	void * cptr; // For 32-bit and 64-bit
	CValue * expRet;
}
-(int)getNumberOfConditions;
-(int)handleRunObject;
-(BOOL)createRunObject:(CFile*)file withCOB:(CCreateObjectInfo*)cob andVersion:(int)version;
-(void)destroyRunObject:(BOOL)bFast;
-(BOOL)condition:(int)num withCndExtension:(CCndExtension*)cnd;
-(void)action:(int)num withActExtension:(CActExtension*)act;
-(CValue*)expression:(int)num;

@end
