/* File generated by DarkEdifPostBuildTool v1.0.1.1, part of DarkEdif SDK.
   DarkEdif license is available at its online repository location.
   Copyright of the Behind The Runtime extension and all rights reserved by creator of Behind The Runtime.

   A native iOS extension needs a Objective-C file to generate a Objective-C class.
   This file is required. The Behind The Runtime creator may modify the copyright to suit their wishes,
   if they retain the preceding DarkEdif notice.
*/

//----------------------------------------------------------------------------------
//
// CRunBehind_The_Runtime
//
//----------------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "CRunExtension.h"
#import "CExtStorage.h"
#import "CCreateObjectInfo.h"

#if __cplusplus
extern "C" void Behind_The_Runtime_init();
extern "C" void Behind_The_Runtime_dealloc();
// Doesn't take a cptr, but you can't use it without SDK initialization - Behind_The_Runtime_init()
extern "C" int Behind_The_Runtime_getNumberOfConditions();
extern "C" long Behind_The_Runtime_conditionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void Behind_The_Runtime_actionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void Behind_The_Runtime_expressionJump(void * cppExtPtr, int ID);
extern "C" void * Behind_The_Runtime_createRunObject(void* file, void * cob, int version, void * objCExtPtr);
extern "C" short Behind_The_Runtime_handleRunObject(void * cppExtPtr);
extern "C" void Behind_The_Runtime_destroyRunObject(void * cppExtPtr, bool bFast);
#endif

static int initedBehind_The_RuntimeCPP = 0;

@interface CRunBehind_The_Runtime : CRunExtension
{
@public
	void * safetyPtr; // used to ensure cptr lookups are using a valid pointer
	void * cptr; // For 32-bit and 64-bit
	CValue * expRet;
}
-(int)getNumberOfConditions;
-(int)handleRunObject;
-(BOOL)createRunObject:(CFile*)file withCOB:(CCreateObjectInfo *)cob andVersion:(int)version;
-(void)destroyRunObject:(BOOL)bFast;
-(BOOL)condition:(int)num withCndExtension:(CCndExtension*)cnd;
-(void)action:(int)num withActExtension:(CActExtension*)act;
-(CValue*)expression:(int)num;

@end
