/* File generated by DarkEdifPreBuildTool v1.0.1.1, part of DarkEdif SDK.
   DarkEdif license is available at its online repository location.
   Copyright of the WIN ICO extension and all rights reserved by creator of WIN ICO.

   A native Mac extension needs a Objective-C file to generate a Objective-C class.
   This file is required. The WIN ICO creator may modify the copyright to suit their wishes,
   if they retain the DarkEdif notice (third line).
*/

//----------------------------------------------------------------------------------
// CRunWIN_ICO
//----------------------------------------------------------------------------------

#import <Foundation/Foundation.h>
#import "MMF2Lib/MMF2Runtime.h"

#if __cplusplus
extern "C" void WIN_ICO_init();
extern "C" void WIN_ICO_dealloc();
// Doesn't take a cptr, but you can't use it without SDK initialization - WIN_ICO_init()
extern "C" int WIN_ICO_getNumberOfConditions();
extern "C" long WIN_ICO_conditionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void WIN_ICO_actionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void WIN_ICO_expressionJump(void * cppExtPtr, int ID);
extern "C" void * WIN_ICO_createRunObject(void * file, void * cob, int version, void * objCExtPtr);
extern "C" short WIN_ICO_handleRunObject(void * cppExtPtr);
extern "C" void WIN_ICO_destroyRunObject(void * cppExtPtr, bool bFast);
extern "C" void WIN_ICO_pauseRunObject(void * cppExtPtr);
extern "C" void WIN_ICO_continueRunObject(void * cppExtPtr);
#endif

static int initedWIN_ICOCPP = 0;

@interface CRunWIN_ICO : CRunExtension
{
@public
	void * safetyPtr; // used to ensure cptr lookups are using a valid pointer
	void * cptr; // For 32-bit and 64-bit
	CValue * expRet;
}
-(int)getNumberOfConditions;
-(int)handleRunObject;
-(BOOL)createRunObject:(CFile*)file withCOB:(CCreateObjectInfo*)cob andVersion:(int)version;
-(void)destroyRunObject:(BOOL)bFast;
-(BOOL)condition:(int)num withCndExtension:(CCndExtension*)cnd;
-(void)action:(int)num withActExtension:(CActExtension*)act;
-(CValue*)expression:(int)num;
-(void)pauseRunObject;
-(void)continueRunObject;

@end
